// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDhzqGreRaaH6VUtSR5PLlP_1Pt5krdmQ',
    appId: '1:68926617765:web:6f1e0d5ca149384fbe754c',
    messagingSenderId: '68926617765',
    projectId: 'travel-website-5b02d',
    authDomain: 'travel-website-5b02d.firebaseapp.com',
    databaseURL: 'https://travel-website-5b02d-default-rtdb.firebaseio.com',
    storageBucket: 'travel-website-5b02d.appspot.com',
    measurementId: 'G-5CNWK25S22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2DX0pVNBNovliJr7X3mt_ZIy3fKNyS4',
    appId: '1:68926617765:android:05170fb177c824edbe754c',
    messagingSenderId: '68926617765',
    projectId: 'travel-website-5b02d',
    databaseURL: 'https://travel-website-5b02d-default-rtdb.firebaseio.com',
    storageBucket: 'travel-website-5b02d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJRLmGDodmlyXrWIiGZXrae4Z5XrCG9E',
    appId: '1:68926617765:ios:0e1e76e508cf3947be754c',
    messagingSenderId: '68926617765',
    projectId: 'travel-website-5b02d',
    databaseURL: 'https://travel-website-5b02d-default-rtdb.firebaseio.com',
    storageBucket: 'travel-website-5b02d.appspot.com',
    iosClientId: '68926617765-m8pghdpdqsatav7elcnmrrjionvva4j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGJRLmGDodmlyXrWIiGZXrae4Z5XrCG9E',
    appId: '1:68926617765:ios:0e1e76e508cf3947be754c',
    messagingSenderId: '68926617765',
    projectId: 'travel-website-5b02d',
    databaseURL: 'https://travel-website-5b02d-default-rtdb.firebaseio.com',
    storageBucket: 'travel-website-5b02d.appspot.com',
    iosClientId: '68926617765-m8pghdpdqsatav7elcnmrrjionvva4j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.travel',
  );
}
